[project]
name = "Classihacking"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "win-64", "linux-64", "osx-64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"
pandas = ">=2.2.2,<2.3"
jupyter = ">=1.0.0,<1.1"
matplotlib = ">=3.8.4,<3.9"
numpy = ">=1.26.4,<1.27"
scikit-learn = ">=1.4.2,<1.5"
seaborn = ">=0.13.2,<0.14"

[target.win-64.dependencies]
python = ">=3.12.8,<4"
matplotlib = ">=3.9.3,<4"
pandas = ">=2.2.3,<3"
scikit-learn = ">=1.6.0,<2"
jupyterlab = ">=4.3.3,<5"
seaborn = ">=0.13.2,<0.14"

[target.linux-64.dependencies]
python = ">=3.12.8,<4"
matplotlib = ">=3.9.3,<4"
pandas = ">=2.2.3,<3"
scikit-learn = ">=1.6.0,<2"
jupyterlab = ">=4.3.3,<5"
seaborn = ">=0.13.2,<0.14"

[target.osx-64.dependencies]
python = ">=3.12.8,<4"
matplotlib = ">=3.9.3,<4"
pandas = ">=2.2.3,<3"
scikit-learn = ">=1.6.0,<2"
jupyterlab = ">=4.3.3,<5"
seaborn = ">=0.13.2,<0.14"

[target.osx-arm64.dependencies]
python = ">=3.12.8,<4"
matplotlib = ">=3.9.3,<4"
pandas = ">=2.2.3,<3"
scikit-learn = ">=1.6.0,<2"
jupyterlab = ">=4.3.3,<5"
seaborn = ">=0.13.2,<0.14"
